# Generated by Django 2.2.2 on 2020-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC_name', models.CharField(max_length=500)),
                ('TC_set_up', models.TextField()),
                ('TC_params', models.TextField()),
                ('TC_checks', models.TextField()),
                ('TC_next_step', models.CharField(max_length=200)),
                ('TC_version', models.CharField(max_length=100)),
            ],
        ),
    ]
