# Generated by Django 2.2 on 2020-07-18 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用例描述')),
                ('url', models.CharField(max_length=100, verbose_name='请求地址')),
                ('method', models.CharField(max_length=20, verbose_name='请求方法')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='登录邮箱')),
                ('pw', models.CharField(blank=True, max_length=20, null=True, verbose_name='登录密码')),
                ('project', models.CharField(max_length=20, verbose_name='项目')),
                ('iteration', models.CharField(max_length=20, verbose_name='迭代版本')),
                ('su_env', models.TextField(blank=True, max_length=200, null=True, verbose_name='前提条件设置')),
                ('params', models.TextField(max_length=200, verbose_name='请求参数')),
                ('ret', models.TextField(blank=True, max_length=200, null=True, verbose_name='接口响应')),
                ('checker', models.TextField(max_length=100, verbose_name='检验')),
                ('next_step', models.TextField(blank=True, max_length=100, null=True, verbose_name='多业务数据')),
                ('td_env', models.TextField(blank=True, max_length=200, null=True, verbose_name='清理数据')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后维护时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='维护人员')),
            ],
            options={
                'verbose_name': '用例描述',
                'verbose_name_plural': '用例描述',
            },
        ),
    ]
