# Generated by Django 2.2.2 on 2020-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用例描述'),
        ),
    ]
