# Generated by Django 2.2.2 on 2020-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpTest', '0002_auto_20200707_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='TC_project',
            field=models.CharField(blank=True, default='Seller', max_length=50, null=True, verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='TC_remark',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
    ]
